development:
  bucket_name: radicaldesigns.org
  access_key_id: 0EMBYWPC81YB9F3X2T02
  secret_access_key: G9HYPHkWCuSiG6YrZJLQLinMxMSQ8x9ajIx9deUj

test:
  bucket_name: radicaldesigns.org
  access_key_id: 0EMBYWPC81YB9F3X2T02
  secret_access_key: G9HYPHkWCuSiG6YrZJLQLinMxMSQ8x9ajIx9deUj

production:
  bucket_name: radicaldesigns.org
  access_key_id: 0EMBYWPC81YB9F3X2T02
  secret_access_key: G9HYPHkWCuSiG6YrZJLQLinMxMSQ8x9ajIx9deUj

