development:
  type: pop
  server: npomail.electricembers.net
  username: voicemail@radicaldesigns.org
  password: sunsh1n3
  port: 995
  ssl: true
  sleep: 10

production:
  type: pop
  server: npomail.electricembers.net
  username: voicemail@radicaldesigns.org
  password: sunsh1n3
  port: 995
  ssl: true

test:
  type: pop
  server: npomail.electricembers.net
  username: voicemail@radicaldesigns.org
  password: sunsh1n3
  port: 995
  ssl: true
